### ISSUE TITLE
Quarry Operating Crashes Server

### ISSUE THREAD

**Issue by windowslogic** [TED-inc/FabricQuarry#1]
When activating the quarry with generated Tech Reborn power, it crashes the server when it gets to 100% for some reason, is this a bug? Does my server not have enough power?

**Comment by TED-inc** [comment]
Yes, It is a bug. Please, send me crash log

**Comment by TED-inc** [comment]
Please, check, is it helps or not
[quarry-reborn-1.17-0.1.1.jar.zip](https://github.com/TED-inc/FabricQuarry/files/6973760/quarry-reborn-1.17-0.1.1.jar.zip)

**Comment by windowslogic** [comment]
Crashed the internal server with this error code: 
The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: 'void reborncore.common.util.RebornInventory.setHashChanged()'
Exit Code: -1

**Comment by TED-inc** [comment]
Which Reborn Core version are you using? 5.0.5 ? This method has been renamed

**Comment by windowslogic** [comment]
I'm using the one included in the Tech Reborn mod, I'm not sure which version it is.

**Comment by TED-inc** [comment]
Try add separate Reborn Core 5.0.5, and check if it helps

**Comment by windowslogic** [comment]
Added Reborn Core and now my game won't load. Shows error code:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'techreborn'!
Exit Code: -1

**Comment by TED-inc** [comment]
Could you make an archive with your mods folder, and send me?

**Comment by windowslogic** [comment]
The only difference to mine and this is the Quarry Reborn 1.1 jar you sent me.

https://windowslogic.keybase.pub/RealitySMP/RealitySMP%20Mods%205.2.zip?dl=1

**Comment by TED-inc** [comment]
You should update TechReborn to 5.0.5 (RebornCore not required), and it will work properly 👌 And please, use 0.1.1 version of QuarryReborn, it much more optimized. Please, let me know, if it help on server side

**Comment by windowslogic** [comment]
Okay, thank you for the help in solving this issue :)
