### ISSUE TITLE
Ancient Debris Does Not Count As An Instance Of An OreBlock

### ISSUE THREAD

**Issue by ghost** [TED-inc/FabricQuarry#11]
Ancient Debris in Minecraft's code just counts as a regular Block and since it doesn't have a manual check like RedstoneOre does, it does not get mined in the mine ores mode of the quarry. I would like to ask for Ancient Debris to be added to the list of ores to be checked for when mining. Thanks!

**Comment by TED-inc** [comment]
I forget about it. I will add it

**Comment by TED-inc** [comment]
fixed in 0.4.1
