### ISSUE TITLE
[suggestion] Range Expansion and Potential Speed Increase

### ISSUE THREAD

**Issue by Frankiscophil** [TED-inc/FabricQuarry#13]
Hello there! I stumbled upon this mod and tested it out in some worlds and modpacks and I gotta say, I love this Quarry. More specifically, its ability to excavate an entire area which is wonderful! But I feel it's a bit limiting in how it can only mine a 16x16 area.

I'd like to ask if there's any future plans to be able to increase the range of the Quarry or even dictate the range yourself with Markers of some kind, similar to the Buildcraft Quarry. I'm hoping for the latter.

Also something I would like but not as much as the ability to scale the Quarry range but would it be too much to bump up the speed of the machine when having four Overclocker Upgrades? Maybe a similar processing speed like the Tech Reborn Electric Furnace? Just something I also wanted to ask.

Having a fun with this mod and I hope you keep on developing this kind of stuff because it is very fun to play with. Have a good day!

**Comment by TED-inc** [comment]
Thanks for your words, I'm happy to create something which is useful 😄 

About your suggestions:
- Increase the range: I have an idea to make it multiblock, but it not in plan currently
- Markers area dictation: I don't want to overcomplicate this mod. Maybe range buttons, like in Fusion Control Computer - is maximum
- Speed Increase: I think for now it fast enough. If u wand more speed - u can place more Quarries
<img src="https://user-images.githubusercontent.com/31252422/133768909-afd85169-4095-42c2-9b1d-cde508e291a8.png"  width="200" height="200" />

And of course, u can change configuration file for your needs
