### ISSUE TITLE
Quarry lost some pipes

### ISSUE THREAD

**Issue by imcasper** [TED-inc/FabricQuarry#16]
**version**
quarry-reborn-1.16-0.4.0.jar

**long description**
Let's say I am at an altitude of 60. I am putting some pipes into a quarry. And I run away for a long time. I come running and add more pipes. I'm running away. Then again. And it seems that there were already about 100 of them. The last time I recorded for sure that there were 60 pipes in the quarry (at a height of 67). When they ended, I put another 12 (or 16 pipes), but they still did not reach the bottom.

As a result, the pipes apparently still reach the bottom and fold back. But (subjectively) it seems to me that the part disappears at some stage.

- I note that this is a home server - which means I turn it on and off every day (possibly in this place of the problem).
- Probably a problem when changing the quarry mode. 
- I use "applied energetic 2" mod for extract ores (i not founded lost pipes in my network)
- 
I would have thought it was part of the mechanics if the pipes weren't quite expensive. 

PS I think this is the best mod quarry [for fabric]

**Comment by TED-inc** [comment]
Thank you for detailed bug report ☺️ I fixed it in 0.4.2, please update (currently last version 0.4.3)

**Comment by TED-inc** [comment]
And thanks for your feedback ☺️☺️☺️
