### ISSUE TITLE
[suggestion] various drill (module for quarry)

### ISSUE THREAD

**Issue by imcasper** [TED-inc/FabricQuarry#17]
Main points:
- the drill affects the mining speed.
- some drills have a "silk touch"

Not sure:
- can be made wearable
- can use drills from the main mod

**Comment by TED-inc** [comment]
I thought a lot about this. But for now I didn't find a good solution, which will be industrial-like

**Comment by TED-inc** [comment]
implement it in some kind at 0.5.0
