### ISSUE TITLE
[bug | 0.4.3] Quarry doesn't mine below 0

### ISSUE THREAD

**Issue by bioa10** [TED-inc/FabricQuarry#22]
**Describe the bug**
When world height extends below 0, such as with the caves and cliffs addon, the quarry stops at 0 and doesn't mine any further.

**Expected behavior**
Expected the quarry to mine down until bedrock.

**Mods versions:**
 - Quarry Reborn: 0.4.3
 - Tech Reborn: 5.0.8
 - Fabric API: 0.40.1

**Comment by TED-inc** [comment]
I will fix it

**Comment by TED-inc** [comment]
fixed in 0.4.4
