### ISSUE TITLE
[suggestion] Quarry Tube Modpack Compatibility

### ISSUE THREAD

**Issue by Frankiscophil** [TED-inc/FabricQuarry#23]
**Is your feature request related to a problem? Please describe.**
The most recent version of All of Fabric 4 has this mod added in its list and I was happily excited to use this Quarry. The only issue is that the Quarry Tubes can't be crafted as Tech Reborn Steel Plates are substituted with Modern Industrialization Steel Plates in the modpack.

**Describe the solution you'd like**
I don't know too much about how this goes but I'd like for the recipe of the Quarry Tubes to be compatible with Steel Plates from other mods, mainly Modern Industrialization and Industrial Revolution.

**Comment by TED-inc** [comment]
In 0.4.4 :
- change crafting recopies items to tags (allow use material not only from tech reborn, modern industrialization for example) 
- change ore find method for more general (now specific ores from other mods must be mined)
