### ISSUE TITLE
Unneeded files inside the mod archive.

### ISSUE THREAD

**Issue by K0-RR** [TED-inc/FabricQuarry#24]
/assets/quarrymod/textures/block/machines/tier2_machines/ contains pdn files alongside png ones which is no use for a non-moder/designer and it doubles the mod weight.
https://github.com/TED-inc/FabricQuarry/tree/master/src/main/resources/assets/quarrymod/textures/block/machines/tier2_machines

**Comment by TED-inc** [comment]
Mod weight is 78.6 KB. Are u serious?

**Comment by K0-RR** [comment]
Yes? How does the weight matter? It’s just something that shouldn’t be in the end product. I would report it even if it weighted 5% of the mod.

**Comment by TED-inc** [comment]
So, is there any real reason to delete it from build jar? Does it create some bugs or issues? If no - I will leave it because it is comfortable for me. Here is much more prioritize tasks such as new features or refactoring of quarry logic code.
