### ISSUE TITLE
[bug | 0.5.0] Full power before setup

### ISSUE THREAD

**Issue by TheRealM18** [TED-inc/FabricQuarry#25]
I was testing in singleplayer, and found out that if you put a creative solar beside the quarry, and has not been setup before the whole process is full, it will make the quarry not to be able to work at all.

I was able to fix it, by setting it up first, then giving it power.

**Comment by TED-inc** [comment]
Thx for report, I will look on it

**Comment by TED-inc** [comment]
Can't reproduce it. Did u gave quarry tubes after charging?

**Comment by TheRealM18** [comment]
I can't remember, but was able to do it multiple times.  Maybe I was not able to get the pipes in fast enough too.

**Comment by TheRealM18** [comment]
![image](https://user-images.githubusercontent.com/5025664/140440380-d396bbc4-3bf9-4761-8227-dab5c08b1329.png)
I think it is the action is do for the tubes, and not able to continue for action to start.  and yes I is 0.5.1

**Comment by TheRealM18** [comment]
You require a inventory to give the tube to the machine.  This is an issue, as if do not know that, I assumed that I could just place them there, without the inventory connected to it.

**Comment by TED-inc** [comment]
U mean change error description? And could you write steps to reproduce this bug, because for now I can't find a way to do it

**Comment by TheRealM18** [comment]
To reproduce the error, here are the following steps:

1) Place down the quarry.
2) Place inside the quarry the quarry tubes, without going through an external inventory.
3) Give the quarry power.

This should give the error, as I should not need to configure them into the configuration tab to get it to work.

**Comment by TED-inc** [comment]
What u mean by external inventory? Something like chest or hopper? So I need to place it manually, in quarry inventory?

**Comment by TheRealM18** [comment]
Yes, you will need to place it in manually into its slots.  a hopper or chest is how it works now, just not manually placed in.

**Comment by TED-inc** [comment]
Trying to reproduce
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/31252422/140602245-3880a123-c067-438d-bfc7-d7f4e32e8f49.gif)

**Comment by TheRealM18** [comment]
allow the full process to reach max before adding them then. I will try to make a gif, or maybe the mod is still out of date.

**Comment by TheRealM18** [comment]
Somehow it's fixed in 0.5.2. Not sure how, but is. If you want to close this ticket you can.

**Comment by TED-inc** [comment]
Happy to hear. Anyway, thanks for reporting.
