### ISSUE TITLE
[suggestion] built-in chunk loader in quarry

### ISSUE THREAD

**Issue by RammasunW** [TED-inc/FabricQuarry#30]
**Is your feature request related to a problem? Please describe.**
It will be better if there's a built-in chunk loader, therefore quarry will always work without forced loading or other mods. I'm not sure whether this feature already exists or not. And I don't find a chunk loader mod for fabric 1.18 as well :/

**Describe the solution you'd like**
Toggle chunk loading mode to make quarry available to load nearby chunks.

**Comment by TED-inc** [comment]
Tech reborn already have [chunk loader](https://wiki.techreborn.ovh/doku.php?id=blocks:industrial_chunkloader), so I don't think this feature necessary. Anyway, thanks for your idea!
