### ISSUE TITLE
[bug | v:0.5.3] "Industrial" in the mod name is spelled incorrectly

### ISSUE THREAD

**Issue by Vapaman** [TED-inc/FabricQuarry#32]
**Describe the bug**
A minor typo in the mod name Industrial is spelled "Industial"
![kuva](https://user-images.githubusercontent.com/77460466/148661339-beb7853e-998a-4a75-829d-339db5edb791.png)
![kuva](https://user-images.githubusercontent.com/77460466/148661426-f3d24925-4383-4649-8312-cfd69d19b574.png)

**Expected behavior**
Correct name would be "Industrial Quarry Mod"
**Mods versions:**
 - Quarry Reborn: 0.5.3
 - Tech Reborn: 5.1.0-beta.5
 - Fabric API: 0.45.2

**Comment by TED-inc** [comment]
Thanks for ur report! Fixed in 0.5.4
