### ISSUE TITLE
[BUG] Crashing involving a sound issue, possible inpompatibility

### ISSUE THREAD

**Issue by snotknobbel** [TED-inc/FabricQuarry#38]
**Describe the bug**
A incompatibility issue is causing a crash when turning on the quarry
it has to do with a certain sound issue

**Steps to Reproduce**
Install tech reborn
Install other mods
turn on the quarry
crash: server closed

**Screenshots**
n.a.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric 0.13.1
 - newest version of tech reborn

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://p.sc2.nl/PK2s9

**Additional context**
n.a.

**Comment by snotknobbel** [comment]
This is for the 1.18.1 version, can there be a fix for that version? Our modpack can't use 1.18.2

**Comment by TED-inc** [comment]
Which exact version of Quarry Reborn and Tech Reborn you are using?

**Comment by snotknobbel** [comment]
I'm using quarry-reborn-1.18-0.5.5
and TechReborn-5.1.0.jar

**Comment by TED-inc** [comment]
This bug was fixed in latest version QR 0.5.6, please use this one
