### ISSUE TITLE
[bug | 0.7.2] Quarry appears "frozen", does not actually break any blocks

### ISSUE THREAD

**Issue by NobleDraconian** [TED-inc/FabricQuarry#44]
**Describe the bug**
Currently, as of `v0.7.2`, it appears the quarry simply freezes when powered, and it continually re-mines the same block over and over again.

**To Reproduce**
1) Run minecraft `v0.18.2` with the following mods:
```
- Fabric API 0.55.1+1.18.2
- Tech Reborn 5.2.0
- Reborn Core 5.20
- Quarry Reborn 0.7.2
```
2) Power up the quarry, give it drill pipes, etc. Set the mode to "mine all"
3) Observe that the quarry is "mining" blocks, but it's not actually mining anything:

https://user-images.githubusercontent.com/26460940/174711102-8a5b015c-3ac5-4fc6-ad92-614849d3d4ea.mp4

**Expected behavior**
It is expected that the quarry would actually mine blocks & create a hole (which can then be filled by the quarry as it mines), like demonstrated on the mod's curseforge page.

**Mods versions:**
 - Quarry Reborn: 0.7.2
 - Tech Reborn: 5.2.0
 - Fabric API: 0.55.1+1.18.2

**Comment by DissiNL** [comment]
Hi,
I will check it and keep you posted.

**Comment by DissiNL** [comment]
It seems it is currently mining in a square but underground so it is not visible.
Could you verify that at the level of the tube, the quarry is excavating an area in a block sized pattern?

What you would see:
![image](https://user-images.githubusercontent.com/10036243/174732056-47148091-2096-4dd9-955a-02cecc7cffe2.png)
![image](https://user-images.githubusercontent.com/10036243/174732956-01310511-2639-4a01-84d8-3a29ed81f4b1.png)

vs what happens:

![image](https://user-images.githubusercontent.com/10036243/174732176-61c8af5b-792e-47ff-8b08-eb38b424078c.png)


If you enable the mine-all halfway through the following will happen:

At the level the tube is, a square will be mined from the lowest X to the highest X. After that the mining will move to the next Z and perform the mining again from lowest X to highest X.


A way to re-mine the entire area is to pick up the quarry tube that currently lives there.

**Comment by NobleDraconian** [comment]
Hi, I've verified that it is infact doing what you described! I don't believe it's a bug, it just led to some confusion on my end.

**Comment by DissiNL** [comment]
I can mark it as an improvement and circle out from the center, it makes more sense as the quarry tube should have access:

![image](https://user-images.githubusercontent.com/10036243/174765951-bd1e2689-0737-428a-bd73-de6888c8f56c.png)

Starting from the middle and going outwards. It will mine a square to not break compatibility but it does make sense to have it going outwards from the middle. I will mark it as improvement.

**Comment by DissiNL** [comment]
![image](https://user-images.githubusercontent.com/10036243/174806349-257053d4-8ef6-4271-91cc-bd922809ebb4.png)

@NobleDraconian Would this be more what you expected? I'll create a change so it will be usable.

https://github.com/TED-inc/FabricQuarry/pull/45

**Comment by NobleDraconian** [comment]
Yeah, that's more expected behavior I'd say!

**Comment by DissiNL** [comment]
It should be available for 1.18.2:

https://github.com/TED-inc/FabricQuarry/releases/tag/0.7.3


https://www.curseforge.com/minecraft/mc-mods/quarry-reborn/files/3842992 (pending approval)

Let us know if it works 😄

**Comment by NobleDraconian** [comment]
I'll take a look later today when I'm off work!

**Comment by NobleDraconian** [comment]
Just tested it, it works!

**Comment by DissiNL** [comment]
Awesome, thanks for verifying 😄
