### ISSUE TITLE
[bug | 1.0.1] Server startup crash

### ISSUE THREAD

**Issue by Geartwo** [TED-inc/FabricQuarry#47]
**Describe the bug**
On my Linux Server with multiple mods there is a querrymod crash on startup

**To Reproduce**
1. Start server
2. Crash

See: https://pastebin.com/kTDmzSVv

**Expected behavior**
The server to start without a crash

**Mods versions:**
 - Quarry Reborn: 1.0.1
 - Tech Reborn: 5.3.0
 - Fabric API: 0.56.3

**Comment by DissiNL** [comment]
Can you provide a list of mods used?
It's been tested with better end and others.

The erroring line of code does not yield any weird quirks: https://github.com/TED-inc/FabricQuarry/blob/1.19/src/main/java/net/quarrymod/RegistryManager.java#L34

**Comment by Geartwo** [comment]
I've made a test instance with only FabricAPI + Techreborn + Querry Reborn.

Same error:
https://pastebin.com/JpRpVHHE

Dedicated server start parameter:
 java -Xmx2G -jar fabric-server-mc.1.19-loader.0.14.8-launcher.0.11.0.jar nogui

Without Querry Reborn the server starts without an error.

**Comment by DissiNL** [comment]
Might be due to a change in the fabric api.
I will have access to a development environment next Wednesday.

In the meantime, you should be able to use fabric 0.55.3. it's been tested with this without an issue. 
fabric_version=0.55.3+1.19

I will update the dependencies when I have access to an environment again. Sorry for the inconvenience

**Comment by GWolf101** [comment]
> In the meantime, you should be able to use fabric 0.55.3. it's been tested with this without an issue.
> fabric_version=0.55.3+1.19

I've been utilizing this version of Fabric, as well as OP's mod versions, and have encountered the same issue.
https://pastebin.com/1E1rhMk6

**Comment by DissiNL** [comment]
I just got back and got a development environment. I will check it now

**Comment by DissiNL** [comment]
Found the issue why it is happning. Will create a fix today. Thanks a lot for the detailed reports 😄 .

**Comment by DissiNL** [comment]
1.0.2 should have the issue solved, it is available here:

https://www.curseforge.com/minecraft/mc-mods/quarry-reborn/files/3862724

And on github:
https://github.com/TED-inc/FabricQuarry/packages/1492943?version=1.0.2

Please let me know if it is working properly for you

**Comment by GWolf101** [comment]
> 1.0.2 should have the issue solved, it is available here:
> 
> https://www.curseforge.com/minecraft/mc-mods/quarry-reborn/files/3862724
> 
> And on github: https://github.com/TED-inc/FabricQuarry/packages/1492943?version=1.0.2
> 
> Please let me know if it is working properly for you

Works perfectly now. Thank you for the help.

**Comment by DissiNL** [comment]
Awesome, thanks for verifying
