### ISSUE TITLE
Overclockers Cause Quarry To Freeze

### ISSUE THREAD

**Issue by windowslogic** [TED-inc/FabricQuarry#6]
If all overclockers are in the "Machine upgrades" panel, the quarry grinds to a hault and gets faster the more overclockers you take out.

**Comment by TED-inc** [comment]
Sounds strange. I tested it, but only at 1.16 . Maybe on 1.17 it works differently

**Comment by TED-inc** [comment]
Cannot reproduce

Tested with:

Minecraft 1.17.1
Fabric 0.11.6
fabric-api-0.37.2+1.17
TechReborn-5.0.6-beta+build.94 _and_ 5.0.5-beta+build.85
quarry-reborn-1.17-0.2.0

https://user-images.githubusercontent.com/31252422/129472131-81f4d588-403a-4790-9be6-6604650afeec.mp4

Please, send me your configuration and video with bug

**Comment by TED-inc** [comment]
Hmm, I think I know possible issue. It can be a problem with not a such powerful power source, which cannot provide so much power. Please, try it with Interdimensional SU, it can provide more 8k energy, which 120% of required for work with 4 overclockers

**Comment by TED-inc** [comment]
Power consume table
|Overclockers count | Total EU per block | Efficient EU/t | Ticks pre block |
|---|---|---|---|
|0|6000|100|60|
|1|10500|233|45|
|2|18375|612|30|
|3|32156|2144|15|
|4|56274|7034|8|

**Comment by windowslogic** [comment]
Ah okay, I'll try with that.

**Comment by TED-inc** [comment]
In 0.2.1 I fixed animation, and now you can configure power consume with config file
