### ISSUE TITLE
What values do I need to choose so the quarry can run overclocked with a medium tier thermal generator?

### ISSUE THREAD

**Issue by windowslogic** [TED-inc/FabricQuarry#7]

**Comment by TED-inc** [comment]
You can calculate the value by this table
|Overclockers count | Total EU per block | Efficient EU/t | Ticks per block |
|---|---|---|---|
|0|6000|100|60|
|1|10500|233|45|
|2|18375|612|30|
|3|32156|2144|15|
|4|56274|7034|8|
