### ISSUE TITLE
[SUGGESTION] Option switch for mining everything

### ISSUE THREAD

**Issue by snaquekiller** [TED-inc/FabricQuarry#8]
Hello,
i use your quarry mod, and i hope to get the cobblestone too.

It's not a bad thing to get only ore and not the cobble, but cobble is usefull :D and the thing is that you don't know where you already put the quarry. and clear the ressource.

So for me a button in the interface maybe for saying get everything could be good :) . 

and for people who just ore, but want to know where they already do the mining, they can activate the option during 2layer and then stop this option .

thank for the mod :)

**Comment by TED-inc** [comment]
Good idea, I will add it in plan

**Comment by imcasper** [comment]
I would be glad even if it could be configured in the server config (quarrymod/machines.json)

**Comment by TED-inc** [comment]
added in 0.4.0
