### ISSUE TITLE
broken tube drop nothing

### ISSUE THREAD

**Issue by imcasper** [TED-inc/FabricQuarry#9]
Breakage of a tube used by a quarry will not drop anything.
I can dig in a mine and accidentally break it.
It would be great if the tube could be put back. 

PS I not sure where i look it:
quarry-reborn-1.16-0.3.0.jar
or 
quarry-reborn-1.16-0.2.1.jar

**Comment by TED-inc** [comment]
Looks like I forgot to add loot table for pipes. I'll fix it

**Comment by TED-inc** [comment]
fixed in 0.4.0
